apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd-community/charts/flux-operator
  ref:
    semver: ">=0.26.0 <1.0.0"
